#!/bin/sh
#
# Copyright (C) 2016 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

tarball="$1"

# Create a temporary working directory.
temp_directory="$(mktemp -d)"

# Download and extract the source.
echo "Downloading '$tarball' and extracting it to '$temp_directory' ..."
curl --fail --location --silent --show-error "$tarball" | tar xz --directory="$temp_directory" --strip-components=1

# Build and install the plugin.
cd "$temp_directory" || exit 1
echo "Starting to build the plugin ..."
make
make install

# Clean-up the source and build files.
rm -r "$temp_directory"
